/* LapKart demo storefront. Product records live here so the catalogue is easy to explain and extend. */
const imageSet = [
  'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80'
];
const laptops = [
 {id:1,name:'Acer Aspire 5',brand:'Acer',category:'Student',processor:'Intel Core i5',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'15.6-inch FHD',price:52990,originalPrice:59990,rating:4.4,badge:'GREAT VALUE'},
 {id:2,name:'Lenovo IdeaPad Slim 3',brand:'Lenovo',category:'Student',processor:'AMD Ryzen 5',ram:'8GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'15.6-inch FHD',price:42990,originalPrice:47990,rating:4.3,badge:'POPULAR'},
 {id:3,name:'HP 15s',brand:'HP',category:'Student',processor:'Intel Core i3',ram:'8GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'15.6-inch FHD',price:36990,originalPrice:41990,rating:4.2,badge:'GREAT VALUE'},
 {id:4,name:'ASUS Vivobook 15',brand:'ASUS',category:'Thin & Light',processor:'Intel Core i5',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'15.6-inch FHD OLED',price:64990,originalPrice:72990,rating:4.5,badge:'POPULAR'},
 {id:5,name:'HP OmniBook X',brand:'HP',category:'AI PC',processor:'Snapdragon X-series',ram:'16GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14-inch 2.2K',price:119990,originalPrice:129990,rating:4.6,badge:'NEW'},
 {id:6,name:'Lenovo Yoga Slim 7',brand:'Lenovo',category:'Thin & Light',processor:'Intel Core Ultra',ram:'16GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14-inch 2.8K OLED',price:109990,originalPrice:119990,rating:4.6,badge:'POPULAR'},
 {id:7,name:'Lenovo ThinkPad E14',brand:'Lenovo',category:'Business',processor:'Intel Core i5',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch FHD',price:74990,originalPrice:82990,rating:4.5,badge:'BESTSELLER'},
 {id:8,name:'HP ProBook 440',brand:'HP',category:'Business',processor:'Intel Core i7',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch FHD',price:89990,originalPrice:99990,rating:4.4,badge:''},
 {id:9,name:'Dell Latitude 3450',brand:'Dell',category:'Business',processor:'Intel Core i5',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch FHD',price:82990,originalPrice:92990,rating:4.3,badge:''},
 {id:10,name:'HP Victus 15',brand:'HP',category:'Gaming',processor:'Intel Core i5',ram:'16GB',storage:'512GB SSD',gpu:'RTX 4050',display:'15.6-inch FHD 144Hz',price:74990,originalPrice:82990,rating:4.5,badge:'BESTSELLER'},
 {id:11,name:'ASUS TUF Gaming A15',brand:'ASUS',category:'Gaming',processor:'AMD Ryzen 7',ram:'16GB',storage:'1TB SSD',gpu:'RTX 4060',display:'15.6-inch FHD 144Hz',price:99990,originalPrice:109990,rating:4.6,badge:'POPULAR'},
 {id:12,name:'Lenovo LOQ 15',brand:'Lenovo',category:'Gaming',processor:'Intel Core i5',ram:'16GB',storage:'512GB SSD',gpu:'RTX 4050',display:'15.6-inch FHD 144Hz',price:84990,originalPrice:92990,rating:4.4,badge:''},
 {id:13,name:'Acer Nitro V 15',brand:'Acer',category:'Gaming',processor:'Intel Core i7',ram:'16GB',storage:'512GB SSD',gpu:'RTX 4060',display:'15.6-inch FHD 165Hz',price:104990,originalPrice:114990,rating:4.5,badge:'NEW'},
 {id:14,name:'MSI Katana 15',brand:'MSI',category:'Gaming',processor:'Intel Core i7',ram:'16GB',storage:'1TB SSD',gpu:'RTX 3050',display:'15.6-inch FHD 144Hz',price:89990,originalPrice:99990,rating:4.5,badge:''},
 {id:15,name:'ASUS ROG Zephyrus G16',brand:'ASUS',category:'Gaming',processor:'Intel Core Ultra',ram:'32GB',storage:'1TB SSD',gpu:'RTX 4070',display:'16-inch QHD OLED',price:219990,originalPrice:239990,rating:4.8,badge:'POPULAR'},
 {id:16,name:'Lenovo Legion Pro 5',brand:'Lenovo',category:'Gaming',processor:'AMD Ryzen 7',ram:'32GB',storage:'1TB SSD',gpu:'RTX 4070',display:'16-inch WQXGA 165Hz',price:194990,originalPrice:214990,rating:4.7,badge:''},
 {id:17,name:'Alienware m16 R2',brand:'Dell',category:'Gaming',processor:'Intel Core Ultra',ram:'32GB',storage:'1TB SSD',gpu:'RTX 4070',display:'16-inch QHD 240Hz',price:279990,originalPrice:299990,rating:4.8,badge:'PREMIUM'},
 {id:18,name:'ASUS ProArt P16',brand:'ASUS',category:'Creator',processor:'AMD Ryzen 9',ram:'32GB',storage:'1TB SSD',gpu:'RTX 4070',display:'16-inch 4K OLED',price:239990,originalPrice:259990,rating:4.7,badge:'NEW'},
 {id:19,name:'Apple MacBook Pro 14',brand:'Apple',category:'Creator',processor:'Apple M-series',ram:'16GB',storage:'512GB SSD',gpu:'Apple Integrated GPU',display:'14-inch Liquid Retina XDR',price:169900,originalPrice:179900,rating:4.8,badge:'POPULAR'},
 {id:20,name:'HP Envy x360 14',brand:'HP',category:'2-in-1',processor:'AMD Ryzen 7',ram:'16GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14-inch 2.8K OLED Touch',price:109990,originalPrice:119990,rating:4.5,badge:''},
 {id:21,name:'Lenovo Yoga 7 2-in-1',brand:'Lenovo',category:'2-in-1',processor:'Intel Core Ultra',ram:'16GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14-inch 2.8K OLED Touch',price:124990,originalPrice:134990,rating:4.6,badge:'NEW'},
 {id:22,name:'Lenovo ThinkPad P16s',brand:'Lenovo',category:'Workstation',processor:'AMD Ryzen 7',ram:'32GB',storage:'1TB SSD',gpu:'RTX 4050',display:'16-inch WUXGA',price:159990,originalPrice:174990,rating:4.5,badge:''},
 {id:23,name:'Dell Precision 3591',brand:'Dell',category:'Workstation',processor:'Intel Core Ultra',ram:'64GB',storage:'1TB SSD',gpu:'RTX 4060',display:'15.6-inch FHD',price:189990,originalPrice:204990,rating:4.6,badge:''},
 {id:24,name:'Dell XPS 14',brand:'Dell',category:'Premium',processor:'Intel Core Ultra',ram:'32GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14.5-inch 3.2K OLED',price:199990,originalPrice:219990,rating:4.7,badge:'PREMIUM'},
 {id:25,name:'Apple MacBook Air 15',brand:'Apple',category:'Premium',processor:'Apple M-series',ram:'16GB',storage:'512GB SSD',gpu:'Apple Integrated GPU',display:'15.3-inch Liquid Retina',price:144900,originalPrice:154900,rating:4.8,badge:'BESTSELLER'},
 {id:26,name:'Samsung Galaxy Book4 Edge',brand:'Samsung',category:'AI PC',processor:'Snapdragon X-series',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch AMOLED',price:124990,originalPrice:134990,rating:4.5,badge:'NEW'},
 {id:27,name:'ASUS Vivobook S 14 OLED',brand:'ASUS',category:'AI PC',processor:'Intel Core Ultra',ram:'16GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14-inch 3K OLED',price:94990,originalPrice:104990,rating:4.5,badge:'POPULAR'},
 {id:28,name:'Acer Swift Go 14',brand:'Acer',category:'Thin & Light',processor:'Intel Core Ultra',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch 2.8K OLED',price:89990,originalPrice:99990,rating:4.4,badge:'GREAT VALUE'},
 {id:29,name:'ASUS ExpertBook B1',brand:'ASUS',category:'Business',processor:'Intel Core i3',ram:'8GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'15.6-inch FHD',price:38990,originalPrice:42990,rating:4.1,badge:'GREAT VALUE'},
 {id:30,name:'Dell Inspiron 14',brand:'Dell',category:'Student',processor:'Intel Core i5',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch FHD+',price:57990,originalPrice:62990,rating:4.3,badge:''},
 {id:31,name:'Acer Aspire 7',brand:'Acer',category:'Gaming',processor:'AMD Ryzen 5',ram:'16GB',storage:'512GB SSD',gpu:'RTX 3050',display:'15.6-inch FHD 144Hz',price:69990,originalPrice:76990,rating:4.3,badge:'POPULAR'},
 {id:32,name:'Dell G15',brand:'Dell',category:'Gaming',processor:'Intel Core i7',ram:'16GB',storage:'1TB SSD',gpu:'RTX 4060',display:'15.6-inch FHD 165Hz',price:119990,originalPrice:129990,rating:4.5,badge:''},
 {id:33,name:'MSI Stealth 16 AI Studio',brand:'MSI',category:'Creator',processor:'Intel Core Ultra',ram:'32GB',storage:'1TB SSD',gpu:'RTX 4070',display:'16-inch QHD+ 240Hz',price:229990,originalPrice:249990,rating:4.7,badge:'NEW'},
 {id:34,name:'Apple MacBook Pro 16',brand:'Apple',category:'Creator',processor:'Apple M-series',ram:'32GB',storage:'1TB SSD',gpu:'Apple Integrated GPU',display:'16-inch Liquid Retina XDR',price:249900,originalPrice:269900,rating:4.9,badge:'PREMIUM'},
 {id:35,name:'Lenovo IdeaPad Flex 5',brand:'Lenovo',category:'2-in-1',processor:'AMD Ryzen 5',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch WUXGA Touch',price:72990,originalPrice:79990,rating:4.4,badge:'POPULAR'},
 {id:36,name:'Samsung Galaxy Book4 Pro',brand:'Samsung',category:'Premium',processor:'Intel Core Ultra',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch 3K AMOLED',price:139990,originalPrice:149990,rating:4.6,badge:''},
 {id:37,name:'HP ZBook Power 16',brand:'HP',category:'Workstation',processor:'Intel Core i7',ram:'64GB',storage:'1TB SSD',gpu:'RTX 4050',display:'16-inch WUXGA',price:174990,originalPrice:189990,rating:4.5,badge:'PRO PICK'},
 {id:38,name:'Lenovo ThinkPad X1 Carbon',brand:'Lenovo',category:'Thin & Light',processor:'Intel Core Ultra',ram:'32GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14-inch 2.8K OLED',price:179990,originalPrice:194990,rating:4.7,badge:'PREMIUM'},
 {id:39,name:'Acer Predator Helios Neo 16',brand:'Acer',category:'Gaming',processor:'Intel Core i7',ram:'32GB',storage:'1TB SSD',gpu:'RTX 4070',display:'16-inch WQXGA 165Hz',price:169990,originalPrice:184990,rating:4.6,badge:'POPULAR'},
 {id:40,name:'ASUS Zenbook 14 OLED',brand:'ASUS',category:'AI PC',processor:'AMD Ryzen 7',ram:'16GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14-inch 3K OLED',price:99990,originalPrice:109990,rating:4.6,badge:'NEW'}
].map((laptop,index)=>({...laptop,image:imageSet[index%imageSet.length]}));

const categories=[['Student','🎓','Everyday & study','#eef3f7'],['Business','💼','Ready for work','#f2f0e9'],['Gaming','🎮','Power up & play','#f4eceb'],['Creator','🎨','Make something great','#f4edf4'],['Performance','⚡','More power, more room','#f6f1e6'],['Thin & Light','🪶','Light on the move','#eaf2ef'],['2-in-1','🔄','Flex your routine','#f2eef5'],['Workstation','🛠','Professional power','#eeeff4'],['Premium','✨','The finer details','#f5f0e7'],['AI PC','🤖','Meet your AI PC','#eaf0f5']];
const filterDefinitions=[
 ['Category',['All','Student','Gaming','Business','Creator','Thin & Light','2-in-1','Workstation','Premium','AI PC']],
 ['Brand',['HP','Dell','Lenovo','ASUS','Acer','Apple','MSI','Samsung']],
 ['Processor',['Intel Core i3','Intel Core i5','Intel Core i7','Intel Core Ultra','AMD Ryzen 5','AMD Ryzen 7','Apple M-series','Snapdragon X-series']],
 ['RAM',['8GB','16GB','32GB','64GB']],
 ['GPU',['Integrated Graphics','RTX 3050','RTX 4050','RTX 4060','RTX 4070 or higher','Apple Integrated GPU']],
 ['Price',['Under ₹40,000','₹40,000 – ₹60,000','₹60,000 – ₹80,000','₹80,000 – ₹1,00,000','₹1,00,000 – ₹1,50,000','Above ₹1,50,000']]
];
const state={category:'',brand:'',processor:'',ram:'',gpu:'',price:'',query:'',sort:'featured',cart:loadCart(),dealOffset:0};
const $=id=>document.getElementById(id);
const formatPrice=value=>'₹'+Number(value).toLocaleString('en-IN');
function loadCart(){try{const saved=JSON.parse(localStorage.getItem('lapkart-cart')||'[]');return Array.isArray(saved)?saved.filter(item=>laptops.some(l=>l.id===item.id)&&Number.isInteger(item.quantity)&&item.quantity>0):[]}catch{return []}}
function saveCart(){localStorage.setItem('lapkart-cart',JSON.stringify(state.cart))}
function discountOf(product){return Math.max(0,Math.round((product.originalPrice-product.price)/product.originalPrice*100))}
function fallbackImage(img,index){img.onerror=null;img.src=`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="460" viewBox="0 0 800 460"><rect width="800" height="460" fill="#eef2ef"/><ellipse cx="400" cy="383" rx="260" ry="18" fill="#dde5df"/><rect x="177" y="73" width="446" height="285" rx="16" fill="#3b4642"/><rect x="190" y="86" width="420" height="259" rx="8" fill="#dfe9e2"/><path d="M150 358h500l-34 22H183z" fill="#9ba9a1"/><text x="400" y="232" text-anchor="middle" font-family="Arial" font-size="24" fill="#356357">LAPTOP ${index+1}</text></svg>`)}`}
function renderCategories(){const grid=$('categoryGrid');grid.innerHTML=categories.map(([name,icon,desc,bg])=>`<button class="category-card ${state.category===name?'selected':''}" data-category="${name}" style="--category-bg:${bg}" aria-pressed="${state.category===name}"><span class="category-arrow">↗</span><span class="category-icon">${icon}</span><b>${name==='AI PC'?'AI / Copilot+ PCs':name==='2-in-1'?'2-in-1 / Convertible':name+' laptops'}</b><small>${desc}</small></button>`).join('');grid.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{state.category=state.category===button.dataset.category?'':button.dataset.category;syncFilterInputs();renderCategories();renderProducts();$('laptops').scrollIntoView({behavior:'smooth'})}))}
function renderFilterGroups(){ $('filterGroups').innerHTML=filterDefinitions.map(([group,options])=>`<details class="filter-group" open><summary>${group}</summary><div class="filter-options">${options.map((option,index)=>{const key=group.toLowerCase();const checked=key==='category'?((option==='All'&&!state.category)||(option===state.category)):state[key]===option;return `<label class="filter-option"><input type="radio" name="filter-${key}" value="${option}" ${checked?'checked':''}>${option}</label>`}).join('')}</div></details>`).join('');$('filterGroups').querySelectorAll('input').forEach(input=>input.addEventListener('change',()=>{const key=input.name.replace('filter-','');if(key==='category')state.category=input.value==='All'?'':input.value;else state[key]=input.value;renderCategories();renderProducts()}))}
function syncFilterInputs(){renderFilterGroups()}
function getFilteredProducts(){let result=laptops.filter(p=>{const query=state.query.trim().toLowerCase();const matchesQuery=!query||[p.name,p.brand,p.processor,p.gpu,p.category].join(' ').toLowerCase().includes(query);const matchesCategory=!state.category||p.category===state.category||(state.category==='Performance'&&['Gaming','Workstation'].includes(p.category));const matchesBrand=!state.brand||p.brand===state.brand;const matchesProcessor=!state.processor||p.processor===state.processor;const matchesRam=!state.ram||p.ram===state.ram;const matchesGpu=!state.gpu||(state.gpu==='RTX 4070 or higher'?p.gpu.startsWith('RTX 4070')||['RTX 4080','RTX 4090'].some(g=>p.gpu.includes(g)):p.gpu===state.gpu);let matchesPrice=true;const price=p.price;if(state.price){matchesPrice=state.price==='Under ₹40,000'?price<40000:state.price==='₹40,000 – ₹60,000'?price>=40000&&price<=60000:state.price==='₹60,000 – ₹80,000'?price>60000&&price<=80000:state.price==='₹80,000 – ₹1,00,000'?price>80000&&price<=100000:state.price==='₹1,00,000 – ₹1,50,000'?price>100000&&price<=150000:price>150000}return matchesQuery&&matchesCategory&&matchesBrand&&matchesProcessor&&matchesRam&&matchesGpu&&matchesPrice});switch(state.sort){case'price-asc':result.sort((a,b)=>a.price-b.price);break;case'price-desc':result.sort((a,b)=>b.price-a.price);break;case'rating':result.sort((a,b)=>b.rating-a.rating);break;case'discount':result.sort((a,b)=>discountOf(b)-discountOf(a));break}return result}
function productCard(p){const index=p.id-1;return `<article class="product-card"><div class="product-image-wrap"><img class="product-image" src="${p.image}" alt="${p.brand} ${p.name} laptop" loading="lazy" onerror="fallbackImage(this,${index})">${p.badge?`<span class="product-badge">${p.badge}</span>`:''}<span class="product-brand">${p.brand}</span></div><div class="product-info"><span class="product-category">${p.category==='AI PC'?'AI / Copilot+ PC':p.category+' laptop'}</span><h3 class="product-title">${p.name}</h3><div class="spec-list"><span class="spec-item" title="${p.processor}"><span>▣</span>${p.processor}</span><span class="spec-item"><span>▤</span>${p.ram} RAM</span><span class="spec-item"><span>▱</span>${p.storage}</span><span class="spec-item" title="${p.gpu}"><span>◈</span>${p.gpu}</span></div><div class="product-rating"><span class="stars">★★★★${p.rating>=4.7?'★':'☆'}</span><b>${p.rating.toFixed(1)}</b><span>·</span><span>${p.display}</span></div><div class="product-price-row"><b class="product-price">${formatPrice(p.price)}</b><span class="original-price">${formatPrice(p.originalPrice)}</span><span class="discount">${discountOf(p)}% off</span></div><button class="add-cart-button" data-add="${p.id}">Add to cart <span>＋</span></button></div></article>`}
function activeFilterChips(){const chips=[];for(const key of ['category','brand','processor','ram','gpu','price'])if(state[key])chips.push(`<span class="filter-chip">${state[key]}<button data-chip="${key}" aria-label="Remove ${state[key]} filter">×</button></span>`);if(state.query)chips.push(`<span class="filter-chip">“${escapeHtml(state.query)}”<button data-chip="query" aria-label="Clear search">×</button></span>`);return chips.join('')}
function escapeHtml(value){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function renderProducts(){const products=getFilteredProducts();$('resultsInfo').textContent=`Showing ${products.length} of ${laptops.length} laptops`;$('productGrid').innerHTML=products.map(productCard).join('');$('productGrid').hidden=!products.length;$('emptyState').hidden=!!products.length;$('activeFilters').innerHTML=activeFilterChips();$('productGrid').querySelectorAll('[data-add]').forEach(button=>button.addEventListener('click',()=>addToCart(Number(button.dataset.add))));$('activeFilters').querySelectorAll('[data-chip]').forEach(button=>button.addEventListener('click',()=>{state[button.dataset.chip]='';syncFilterInputs();if(button.dataset.chip==='query')$('catalogSearch').value='';renderCategories();renderProducts()}))}
function clearFilters(){state.category=state.brand=state.processor=state.ram=state.gpu=state.price=state.query='';$('catalogSearch').value='';$('navSearch').value='';syncFilterInputs();renderCategories();renderProducts()}
function addToCart(id){const product=laptops.find(p=>p.id===id);const existing=state.cart.find(item=>item.id===id);if(existing)existing.quantity++;else state.cart.push({id,quantity:1});saveCart();renderCart();showToast(`${product.name} added to your cart.`)}
function changeQuantity(id,delta){const item=state.cart.find(entry=>entry.id===id);if(!item)return;item.quantity+=delta;if(item.quantity<=0)state.cart=state.cart.filter(entry=>entry.id!==id);saveCart();renderCart()}
function removeFromCart(id){state.cart=state.cart.filter(item=>item.id!==id);saveCart();renderCart()}
function cartSubtotal(){return state.cart.reduce((total,item)=>total+laptops.find(p=>p.id===item.id).price*item.quantity,0)}
function renderCart(){const count=state.cart.reduce((n,item)=>n+item.quantity,0),subtotal=cartSubtotal(),delivery=subtotal===0||subtotal>=50000?0:99;$('cartCount').textContent=count;$('drawerItemCount').textContent=`(${count})`;$('cartItems').innerHTML=state.cart.map(item=>{const p=laptops.find(product=>product.id===item.id);return `<article class="cart-item"><img src="${p.image}" alt="${p.name}" onerror="fallbackImage(this,${p.id-1})"><div><h3>${p.name}</h3><small>${formatPrice(p.price)} each</small><div class="quantity-control"><button data-qty="${p.id}" data-delta="-1" aria-label="Decrease ${p.name} quantity">−</button><span>${item.quantity}</span><button data-qty="${p.id}" data-delta="1" aria-label="Increase ${p.name} quantity">+</button><button class="remove-item" data-remove="${p.id}">Remove</button></div></div><b class="cart-item-price">${formatPrice(p.price*item.quantity)}</b></article>`}).join('');$('cartItems').querySelectorAll('[data-qty]').forEach(button=>button.addEventListener('click',()=>changeQuantity(Number(button.dataset.qty),Number(button.dataset.delta))));$('cartItems').querySelectorAll('[data-remove]').forEach(button=>button.addEventListener('click',()=>removeFromCart(Number(button.dataset.remove))));$('cartEmpty').hidden=count>0;$('cartSummary').hidden=count===0;$('cartSubtotal').textContent=formatPrice(subtotal);$('cartDelivery').textContent=delivery===0?'FREE':formatPrice(delivery);$('deliveryHint').textContent=subtotal>0&&subtotal<50000?`Add ${formatPrice(50000-subtotal)} more for free delivery`:'Free delivery on orders ₹50,000 and above';$('cartTotal').textContent=formatPrice(subtotal+delivery);$('checkoutTotal').textContent=formatPrice(subtotal+delivery)}
function openCart(){ $('cartDrawer').classList.add('open');$('drawerScrim').classList.add('open');$('cartDrawer').setAttribute('aria-hidden','false');document.body.classList.add('lock-scroll')}
function closeCart(){ $('cartDrawer').classList.remove('open');$('drawerScrim').classList.remove('open');$('cartDrawer').setAttribute('aria-hidden','true');document.body.classList.remove('lock-scroll')}
function showToast(message){const toast=document.createElement('div');toast.className='toast';toast.textContent=message;$('toastRegion').append(toast);setTimeout(()=>toast.remove(),3000)}
function renderDeals(){const discounted=laptops.filter(p=>discountOf(p)>=9).sort((a,b)=>discountOf(b)-discountOf(a));const picks=[0,1].map(offset=>discounted[(state.dealOffset+offset)%discounted.length]);$('dealCards').innerHTML=picks.map(p=>`<article class="deal-card"><img src="${p.image}" alt="${p.name}" loading="lazy" onerror="fallbackImage(this,${p.id-1})"><div class="deal-copy"><span class="deal-label">${discountOf(p)}% OFF</span><h3>${p.name}</h3><small>${p.processor} · ${p.ram} RAM</small><div class="deal-price"><b>${formatPrice(p.price)}</b><del>${formatPrice(p.originalPrice)}</del><span>Save ${formatPrice(p.originalPrice-p.price)}</span></div></div></article>`).join('')}
function openCheckout(){if(!state.cart.length)return;closeCart();$('checkoutBackdrop').classList.add('open');$('checkoutBackdrop').setAttribute('aria-hidden','false');document.body.classList.add('lock-scroll');$('checkoutFormWrap').hidden=false;$('orderSuccess').hidden=true}
function closeCheckout(){ $('checkoutBackdrop').classList.remove('open');$('checkoutBackdrop').setAttribute('aria-hidden','true');document.body.classList.remove('lock-scroll')}
function placeOrder(event){event.preventDefault();const form=$('checkoutForm');if(!form.reportValidity())return;const order=`LPK${Math.floor(10000+Math.random()*90000)}`;$('orderId').textContent=`Order ID: ${order}`;$('checkoutFormWrap').hidden=true;$('orderSuccess').hidden=false;state.cart=[];saveCart();renderCart()}
function bindEvents(){$('catalogSearch').addEventListener('input',event=>{state.query=event.target.value;renderProducts()});$('navSearch').addEventListener('input',event=>{$('catalogSearch').value=event.target.value;state.query=event.target.value;renderProducts()});$('clearSearch').addEventListener('click',()=>{state.query='';$('catalogSearch').value='';$('navSearch').value='';renderProducts()});$('sortSelect').addEventListener('change',event=>{state.sort=event.target.value;renderProducts()});$('clearFilters').addEventListener('click',clearFilters);$('emptyClear').addEventListener('click',clearFilters);$('cartOpen').addEventListener('click',openCart);$('cartClose').addEventListener('click',closeCart);$('drawerScrim').addEventListener('click',closeCart);$('continueShopping').addEventListener('click',()=>{closeCart();$('laptops').scrollIntoView({behavior:'smooth'})});$('checkoutOpen').addEventListener('click',openCheckout);$('checkoutClose').addEventListener('click',closeCheckout);$('checkoutBackdrop').addEventListener('click',event=>{if(event.target===$('checkoutBackdrop'))closeCheckout()});$('checkoutForm').addEventListener('submit',placeOrder);$('orderDone').addEventListener('click',closeCheckout);$('dealPrev').addEventListener('click',()=>{state.dealOffset=(state.dealOffset+1)%laptops.length;renderDeals()});$('dealNext').addEventListener('click',()=>{state.dealOffset=(state.dealOffset+1)%laptops.length;renderDeals()});$('mobileMenuButton').addEventListener('click',()=>{const open=$('navLinks').classList.toggle('open');$('mobileMenuButton').setAttribute('aria-expanded',open)});$('navLinks').querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>$('navLinks').classList.remove('open')));$('filterOpen').addEventListener('click',()=>{$('filterPanel').classList.add('open');$('drawerScrim').classList.add('open');document.body.classList.add('lock-scroll')});$('filterClose').addEventListener('click',closeFilters);$('drawerScrim').addEventListener('click',closeFilters);$('filterPanel').addEventListener('click',event=>event.stopPropagation());document.querySelectorAll('[data-footer-category]').forEach(link=>link.addEventListener('click',()=>{state.category=link.dataset.footerCategory;syncFilterInputs();renderCategories();renderProducts()}));document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeCart();closeCheckout();closeFilters();$('navLinks').classList.remove('open')}})}
function closeFilters(){$('filterPanel').classList.remove('open');if(!$('cartDrawer').classList.contains('open'))$('drawerScrim').classList.remove('open');if(!$('cartDrawer').classList.contains('open')&&!$('checkoutBackdrop').classList.contains('open'))document.body.classList.remove('lock-scroll')}
renderCategories();renderFilterGroups();renderProducts();renderCart();renderDeals();bindEvents();
