/* LapKart demo storefront. Product records live here so the catalogue is easy to explain and extend. */
const productImages = {
  1:'https://static2-ecemea.acer.com/media/catalog/product/_/a/_aspire-5-a515-57-a515-57g-a515-57gt-s50-54-fp-bl-gray_w11_1000main_nx.kn4eg.00c.png',
  2:'https://cdn.jiostore.online/v2/jmd-asp/jdprod/wrkr/products/pictures/item/free/original/lenovo/494494652/0/53n4Z1VAAs-kxgf21PnmZ-Lenovo-83K100CFIN-Laptop-494494652-i-1-1200Wx1200H.jpeg',
  3:'https://gzhls.at/pix/45/cf/45cfff0383760b24-l.webp',
  4:'https://mobileplanet.ua/uploads/product/2025-8-9/asus-vivobook-15-x1504va-quiet-blue-x1504va-bq3123-351557.webp',
  5:'https://hp.widen.net/content/7julidp6ve/webp/7julidp6ve.png?color=ffffff00&dpi=72&w=573',
  6:'https://cdn.media.amplience.net/i/currysprod/10261803?%24l-large%24=&fmt=auto',
  7:'https://images.eprice.it/nobrand/0/hres/581/309554581/ICECAT_fce6fdd6-8c5f-4001-a404-2954f942f23c-0.jpg',
  8:'https://lapvip.com.vn/upload/78781-9h8u6pt-update-1-1920x.jpg',
  9:'https://www.ticktech.com/cdn/shop/files/210-BLLH1.jpg?v=1764783235&width=1600',
  10:'https://cdn.jiostore.online/v2/jmd-asp/jdprod/wrkr/products/pictures/item/free/original/hp/494353349/0/ckK6HKaeqR-EjeXhp5F-7-HP-V15-fa1279TX-494353349-i-1-1200Wx1200H.jpeg',
  11:'https://down-id.img.susercontent.com/file/id-11134207-7r991-lv2xm15n13jx73',
  12:'https://cdn.idealo.com/folder/Product/204458/4/204458407/s1_produktbild_max/lenovo-loq-15-83dv00b1sp.jpg',
  13:'https://cdn.mos.cms.futurecdn.net/faVAW7FwFUKx2ePQsAwcPd.jpg',
  14:'https://assets.msy.com.au/newsite/images/202403/source_img/MSI-Laptops-MSI-Katana-15-B13V-15-6in-FHD-i7-13620H-RTX-4060-512GB-SSD-16GB-RAM-W11H-Gaming-Laptop-KATANA-15-B13VFK-1480AU-4.webp',
  15:'https://dlcdnwebimgs.asus.com/gain/7E2B892B-4955-45FF-827A-6140DBF39BC0/w1000/h732',
  16:'https://hanoicomputercdn.com/media/product/79031_legion_pro_5_16irx9__4_.jpg',
  17:'https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/alienware-notebooks/alienware-m16-r2-intel/spi/ir-perkey/ng/notebook-alienware-m16-r2-ir-perkey-black-compare-800x550-front-v2.png?fmt=png-alpha&hei=550&wid=800',
  18:'https://press.asus.com/assets/w_5000%2Ch_5000/e96933f6-6602-4b32-899c-453352984e60/ProArt%20P16_H7606_Product%20photo_Nano%20Black_03.png',
  19:'https://cdn.comfy.ua/media/catalog/product/m/a/macbook_pro_14_in_m3_pro_max_silver_pdp_image_position-1__en-us_1.jpg',
  20:'https://laptopaz.vn/media/product/3290_hp_envy_x360_14_fa0013dx_2024_1716883081.jpg',
  21:'https://www.notebookcheck-tr.com/uploads/tx_nbc2/Lenovo_Yoga_7_14AHP9__1_.jpg',
  22:'https://p2-ofp.static.pub/fes/cms/2024/04/29/d52rjdjb8nh7m550qqffbv92t3rf07823403.png?height=700&width=700',
  23:'https://i.dell.com/is/image/DellContent/content/dam/images/products/workstations/precision-mobile/15-3591-non-touch/pr3591nt-rgb-cnb-05000ff090-gy.psd?%24S7-480wide%24=&layer=1&perspective=680%2C844%2C4320%2C844%2C4320%2C2901%2C678%2C2901&pos=-291%2C-678&src=is%7BDellContent%2Fadobestock-678716657%3Fsize%3D4000%2C4000%7D',
  24:'https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/14-9440/media-gallery/notebook-xps-14-9440t-sl-gallery-9.psd?chrss=full&fmt=pjpg&hei=2314&imwidth=5000&pscan=auto&qlt=100%2C1&resMode=sharp2&scl=1&size=3676%2C2314&wid=3676',
  25:'https://creativehub.teliacompany.com/m/4794b03dc197573e/original/MacBook_Air_15_in_M3_Space_Gray_PDP_Image_Position_1__WWEN.png',
  26:'https://dazzle.sgp1.cdn.digitaloceanspaces.com/25532/Samsung-Galaxy-Book-4-edge-14.png',
  27:'https://next-media.elkjop.com/image/dv_web_D18000126537984/830776/asus-vivobook-s-14-s5406sa-u5-226v16512oled-14-copilot-pc.jpg',
  28:'https://static-ecpa.acer.com/media/catalog/product/a/c/acer-swift-go-14-sfg14-42-with-fingerprint-with-backlit-on-wallpaper-start-screen-pure-silver-01-1000x1000_nx.kleaa.001.png',
  29:'https://static.msystems.gr/photos/big_photos/49990.jpg',
  30:'https://bf1af2.akinoncloudcdn.com/products/2024/09/23/137274/aa93a99f-d3fa-45c8-aa7e-d6b0d4b20ca9_size1920_cropCenter.jpg',
  31:'https://product.hstatic.net/1000233206/product/acer-aspire-7-a715-59g-57tu_e8d0d6c805be4214b6ebd39f0ba84f43_1024x1024.png',
  32:'https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/g-series/g15-5530/media-gallery/gray/non-touch/4-zone-rgb-kb/notebook-laptop-g15-5530-gray-gallery-1.psd?chrss=full&fmt=pjpg&hei=3108&imwidth=5000&pscan=auto&qlt=100%2C1&resMode=sharp2&scl=1&size=4280%2C3108&wid=4280',
  33:'https://asset.msi.com/resize/image/global/product/product_16993485045244a1898a4b060e4c042e16fc5246b7.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png',
  34:'https://static.swappa.com/media/product/macbook-pro-late-2023-m3-16/macbook-pro-late-2023-m3-16-02.png',
  35:'https://i5.walmartimages.com/seo/Lenovo-IdeaPad-Flex-5-14ALC7-14-Multi-touch-Laptop-AMD-Ryzen-5-5500U-8GB-RAM-256GB-SSD-AMD-Radeon-Graphics-Windows-11-Home-Storm-Grey-82R9000SUS_b9c62196-5f7a-4586-9cfd-1808e1eb60d3.647ea7fea1cdb7674358d88e9eb0604c.jpeg',
  36:'https://cdn.grupoelcorteingles.es/SGFM/dctm/MEDIA03/202403/13/00115215597293____24__1200x1200.jpg',
  37:'https://tweakers.net/ext/i/2006805398.jpeg',
  38:'https://psrefstuff.lenovo.com/syspool/Sys/Image/ThinkPad/ThinkPad_X1_Carbon_Gen_12/ThinkPad_X1_Carbon_Gen_12_CT1_03.png',
  39:'https://product.hstatic.net/200000837185/product/-helios-neo-16-phn16-72-4zone-backlit-on-wallpaper-black-01_7fcb84949cd3421892512c021fa8dee8_master.png',
  40:'https://press.asus.com/assets/w_5000%2Ch_5000/2ba56354-236e-4135-80e2-b004bf77e859/Zenbook%2014_UX3405CA_Product%20photo_3B_Ponder%20Blue_03.png'
};
const laptops = [
 {id:1,name:'Acer Aspire 5',brand:'Acer',category:'Student',processor:'Intel Core i5',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'15.6-inch FHD',price:52990,originalPrice:59990,rating:4.4,badge:'GREAT VALUE'},
 {id:2,name:'Lenovo IdeaPad Slim 3',brand:'Lenovo',category:'Student',processor:'AMD Ryzen 5',ram:'8GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'15.6-inch FHD',price:42990,originalPrice:47990,rating:4.3,badge:'POPULAR'},
 {id:3,name:'HP 15s',brand:'HP',category:'Student',processor:'Intel Core i3',ram:'8GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'15.6-inch FHD',price:36990,originalPrice:41990,rating:4.2,badge:'GREAT VALUE'},
 {id:4,name:'ASUS Vivobook 15',brand:'ASUS',category:'Thin & Light',processor:'Intel Core i5',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'15.6-inch FHD OLED',price:64990,originalPrice:72990,rating:4.5,badge:'POPULAR'},
 {id:5,name:'HP OmniBook X',brand:'HP',category:'AI PC',processor:'Snapdragon X-series',ram:'16GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14-inch 2.2K',price:119990,originalPrice:129990,rating:4.6,badge:'NEW'},
 {id:6,name:'Lenovo Yoga Slim 7',brand:'Lenovo',category:'Thin & Light',processor:'Intel Core Ultra',ram:'16GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14-inch 2.8K OLED',price:109990,originalPrice:119990,rating:4.6,badge:'POPULAR'},
 {id:7,name:'Lenovo ThinkPad E14',brand:'Lenovo',category:'Business',processor:'Intel Core i5',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch FHD',price:74990,originalPrice:82990,rating:4.5,badge:'BESTSELLER'},
 {id:8,name:'HP ProBook 440',brand:'HP',category:'Business',processor:'Intel Core i7',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch FHD',price:89990,originalPrice:99990,rating:4.4,badge:''},
 {id:9,name:'Dell Latitude 3450',brand:'Dell',category:'Business',processor:'Intel Core i5',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch FHD',price:82990,originalPrice:92990,rating:4.3,badge:''},
 {id:10,name:'HP Victus 15',brand:'HP',category:'Gaming',processor:'Intel Core i5',ram:'16GB',storage:'512GB SSD',gpu:'RTX 4050',display:'15.6-inch FHD 144Hz',price:74990,originalPrice:82990,rating:4.5,badge:'BESTSELLER'},
 {id:11,name:'ASUS TUF Gaming A15',brand:'ASUS',category:'Gaming',processor:'AMD Ryzen 7',ram:'16GB',storage:'1TB SSD',gpu:'RTX 4060',display:'15.6-inch FHD 144Hz',price:99990,originalPrice:109990,rating:4.6,badge:'POPULAR'},
 {id:12,name:'Lenovo LOQ 15',brand:'Lenovo',category:'Gaming',processor:'Intel Core i5',ram:'16GB',storage:'512GB SSD',gpu:'RTX 4050',display:'15.6-inch FHD 144Hz',price:84990,originalPrice:92990,rating:4.4,badge:''},
 {id:13,name:'Acer Nitro V 15',brand:'Acer',category:'Gaming',processor:'Intel Core i7',ram:'16GB',storage:'512GB SSD',gpu:'RTX 4060',display:'15.6-inch FHD 165Hz',price:104990,originalPrice:114990,rating:4.5,badge:'NEW'},
 {id:14,name:'MSI Katana 15',brand:'MSI',category:'Gaming',processor:'Intel Core i7',ram:'16GB',storage:'1TB SSD',gpu:'RTX 3050',display:'15.6-inch FHD 144Hz',price:89990,originalPrice:99990,rating:4.5,badge:''},
 {id:15,name:'ASUS ROG Zephyrus G16',brand:'ASUS',category:'Gaming',processor:'Intel Core Ultra',ram:'32GB',storage:'1TB SSD',gpu:'RTX 4070',display:'16-inch QHD OLED',price:219990,originalPrice:239990,rating:4.8,badge:'POPULAR'},
 {id:16,name:'Lenovo Legion Pro 5',brand:'Lenovo',category:'Gaming',processor:'AMD Ryzen 7',ram:'32GB',storage:'1TB SSD',gpu:'RTX 4070',display:'16-inch WQXGA 165Hz',price:194990,originalPrice:214990,rating:4.7,badge:''},
 {id:17,name:'Alienware m16 R2',brand:'Dell',category:'Gaming',processor:'Intel Core Ultra',ram:'32GB',storage:'1TB SSD',gpu:'RTX 4070',display:'16-inch QHD 240Hz',price:279990,originalPrice:299990,rating:4.8,badge:'PREMIUM'},
 {id:18,name:'ASUS ProArt P16',brand:'ASUS',category:'Creator',processor:'AMD Ryzen 9',ram:'32GB',storage:'1TB SSD',gpu:'RTX 4070',display:'16-inch 4K OLED',price:239990,originalPrice:259990,rating:4.7,badge:'NEW'},
 {id:19,name:'Apple MacBook Pro 14',brand:'Apple',category:'Creator',processor:'Apple M-series',ram:'16GB',storage:'512GB SSD',gpu:'Apple Integrated GPU',display:'14-inch Liquid Retina XDR',price:169900,originalPrice:179900,rating:4.8,badge:'POPULAR'},
 {id:20,name:'HP Envy x360 14',brand:'HP',category:'2-in-1',processor:'AMD Ryzen 7',ram:'16GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14-inch 2.8K OLED Touch',price:109990,originalPrice:119990,rating:4.5,badge:''},
 {id:21,name:'Lenovo Yoga 7 2-in-1',brand:'Lenovo',category:'2-in-1',processor:'Intel Core Ultra',ram:'16GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14-inch 2.8K OLED Touch',price:124990,originalPrice:134990,rating:4.6,badge:'NEW'},
 {id:22,name:'Lenovo ThinkPad P16s',brand:'Lenovo',category:'Workstation',processor:'AMD Ryzen 7',ram:'32GB',storage:'1TB SSD',gpu:'RTX 4050',display:'16-inch WUXGA',price:159990,originalPrice:174990,rating:4.5,badge:''},
 {id:23,name:'Dell Precision 3591',brand:'Dell',category:'Workstation',processor:'Intel Core Ultra',ram:'64GB',storage:'1TB SSD',gpu:'RTX 4060',display:'15.6-inch FHD',price:189990,originalPrice:204990,rating:4.6,badge:''},
 {id:24,name:'Dell XPS 14',brand:'Dell',category:'Premium',processor:'Intel Core Ultra',ram:'32GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14.5-inch 3.2K OLED',price:199990,originalPrice:219990,rating:4.7,badge:'PREMIUM'},
 {id:25,name:'Apple MacBook Air 15',brand:'Apple',category:'Premium',processor:'Apple M-series',ram:'16GB',storage:'512GB SSD',gpu:'Apple Integrated GPU',display:'15.3-inch Liquid Retina',price:144900,originalPrice:154900,rating:4.8,badge:'BESTSELLER'},
 {id:26,name:'Samsung Galaxy Book4 Edge',brand:'Samsung',category:'AI PC',processor:'Snapdragon X-series',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch AMOLED',price:124990,originalPrice:134990,rating:4.5,badge:'NEW'},
 {id:27,name:'ASUS Vivobook S 14 OLED',brand:'ASUS',category:'AI PC',processor:'Intel Core Ultra',ram:'16GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14-inch 3K OLED',price:94990,originalPrice:104990,rating:4.5,badge:'POPULAR'},
 {id:28,name:'Acer Swift Go 14',brand:'Acer',category:'Thin & Light',processor:'Intel Core Ultra',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch 2.8K OLED',price:89990,originalPrice:99990,rating:4.4,badge:'GREAT VALUE'},
 {id:29,name:'ASUS ExpertBook B1',brand:'ASUS',category:'Business',processor:'Intel Core i3',ram:'8GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'15.6-inch FHD',price:38990,originalPrice:42990,rating:4.1,badge:'GREAT VALUE'},
 {id:30,name:'Dell Inspiron 14',brand:'Dell',category:'Student',processor:'Intel Core i5',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch FHD+',price:57990,originalPrice:62990,rating:4.3,badge:''},
 {id:31,name:'Acer Aspire 7',brand:'Acer',category:'Gaming',processor:'AMD Ryzen 5',ram:'16GB',storage:'512GB SSD',gpu:'RTX 3050',display:'15.6-inch FHD 144Hz',price:69990,originalPrice:76990,rating:4.3,badge:'POPULAR'},
 {id:32,name:'Dell G15',brand:'Dell',category:'Gaming',processor:'Intel Core i7',ram:'16GB',storage:'1TB SSD',gpu:'RTX 4060',display:'15.6-inch FHD 165Hz',price:119990,originalPrice:129990,rating:4.5,badge:''},
 {id:33,name:'MSI Stealth 16 AI Studio',brand:'MSI',category:'Creator',processor:'Intel Core Ultra',ram:'32GB',storage:'1TB SSD',gpu:'RTX 4070',display:'16-inch QHD+ 240Hz',price:229990,originalPrice:249990,rating:4.7,badge:'NEW'},
 {id:34,name:'Apple MacBook Pro 16',brand:'Apple',category:'Creator',processor:'Apple M-series',ram:'32GB',storage:'1TB SSD',gpu:'Apple Integrated GPU',display:'16-inch Liquid Retina XDR',price:249900,originalPrice:269900,rating:4.9,badge:'PREMIUM'},
 {id:35,name:'Lenovo IdeaPad Flex 5',brand:'Lenovo',category:'2-in-1',processor:'AMD Ryzen 5',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch WUXGA Touch',price:72990,originalPrice:79990,rating:4.4,badge:'POPULAR'},
 {id:36,name:'Samsung Galaxy Book4 Pro',brand:'Samsung',category:'Premium',processor:'Intel Core Ultra',ram:'16GB',storage:'512GB SSD',gpu:'Integrated Graphics',display:'14-inch 3K AMOLED',price:139990,originalPrice:149990,rating:4.6,badge:''},
 {id:37,name:'HP ZBook Power 16',brand:'HP',category:'Workstation',processor:'Intel Core i7',ram:'64GB',storage:'1TB SSD',gpu:'RTX 4050',display:'16-inch WUXGA',price:174990,originalPrice:189990,rating:4.5,badge:'PRO PICK'},
 {id:38,name:'Lenovo ThinkPad X1 Carbon',brand:'Lenovo',category:'Thin & Light',processor:'Intel Core Ultra',ram:'32GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14-inch 2.8K OLED',price:179990,originalPrice:194990,rating:4.7,badge:'PREMIUM'},
 {id:39,name:'Acer Predator Helios Neo 16',brand:'Acer',category:'Gaming',processor:'Intel Core i7',ram:'32GB',storage:'1TB SSD',gpu:'RTX 4070',display:'16-inch WQXGA 165Hz',price:169990,originalPrice:184990,rating:4.6,badge:'POPULAR'},
 {id:40,name:'ASUS Zenbook 14 OLED',brand:'ASUS',category:'AI PC',processor:'AMD Ryzen 7',ram:'16GB',storage:'1TB SSD',gpu:'Integrated Graphics',display:'14-inch 3K OLED',price:99990,originalPrice:109990,rating:4.6,badge:'NEW'}
].map(laptop=>({...laptop,image:productImages[laptop.id]}));

const categories=[['Student','🎓','Everyday & study','#eef3f7'],['Business','💼','Ready for work','#f2f0e9'],['Gaming','🎮','Power up & play','#f4eceb'],['Creator','🎨','Make something great','#f4edf4'],['Performance','⚡','More power, more room','#f6f1e6'],['Thin & Light','🪶','Light on the move','#eaf2ef'],['2-in-1','🔄','Flex your routine','#f2eef5'],['Workstation','🛠','Professional power','#eeeff4'],['Premium','✨','The finer details','#f5f0e7'],['AI PC','🤖','Meet your AI PC','#eaf0f5']];
const filterDefinitions=[
 ['Category',['All','Student','Gaming','Business','Creator','Thin & Light','2-in-1','Workstation','Premium','AI PC']],
 ['Brand',['HP','Dell','Lenovo','ASUS','Acer','Apple','MSI','Samsung']],
 ['Processor',['Intel Core i3','Intel Core i5','Intel Core i7','Intel Core Ultra','AMD Ryzen 5','AMD Ryzen 7','Apple M-series','Snapdragon X-series']],
 ['RAM',['8GB','16GB','32GB','64GB']],
 ['GPU',['Integrated Graphics','RTX 3050','RTX 4050','RTX 4060','RTX 4070 or higher','Apple Integrated GPU']],
 ['Price',['Under ₹40,000','₹40,000 – ₹60,000','₹60,000 – ₹80,000','₹80,000 – ₹1,00,000','₹1,00,000 – ₹1,50,000','Above ₹1,50,000']]
];
const state={category:'',brand:'',processor:'',ram:'',gpu:'',price:'',query:'',sort:'featured',cart:loadCart(),dealOffset:0};
const $=id=>document.getElementById(id);
const formatPrice=value=>'₹'+Number(value).toLocaleString('en-IN');
function loadCart(){try{const saved=JSON.parse(localStorage.getItem('lapkart-cart')||'[]');return Array.isArray(saved)?saved.filter(item=>laptops.some(l=>l.id===item.id)&&Number.isInteger(item.quantity)&&item.quantity>0):[]}catch{return []}}
function saveCart(){localStorage.setItem('lapkart-cart',JSON.stringify(state.cart))}
function discountOf(product){return Math.max(0,Math.round((product.originalPrice-product.price)/product.originalPrice*100))}
function fallbackImage(img,index){img.onerror=null;img.src=`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="460" viewBox="0 0 800 460"><rect width="800" height="460" fill="#eef2ef"/><ellipse cx="400" cy="383" rx="260" ry="18" fill="#dde5df"/><rect x="177" y="73" width="446" height="285" rx="16" fill="#3b4642"/><rect x="190" y="86" width="420" height="259" rx="8" fill="#dfe9e2"/><path d="M150 358h500l-34 22H183z" fill="#9ba9a1"/><text x="400" y="232" text-anchor="middle" font-family="Arial" font-size="24" fill="#356357">LAPTOP ${index+1}</text></svg>`)}`}
function renderCategories(){const grid=$('categoryGrid');grid.innerHTML=categories.map(([name,icon,desc,bg])=>`<button class="category-card ${state.category===name?'selected':''}" data-category="${name}" style="--category-bg:${bg}" aria-pressed="${state.category===name}"><span class="category-arrow">↗</span><span class="category-icon">${icon}</span><b>${name==='AI PC'?'AI / Copilot+ PCs':name==='2-in-1'?'2-in-1 / Convertible':name+' laptops'}</b><small>${desc}</small></button>`).join('');grid.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{state.category=state.category===button.dataset.category?'':button.dataset.category;syncFilterInputs();renderCategories();renderProducts();$('laptops').scrollIntoView({behavior:'smooth'})}))}
function renderFilterGroups(){ $('filterGroups').innerHTML=filterDefinitions.map(([group,options])=>`<details class="filter-group" open><summary>${group}</summary><div class="filter-options">${options.map((option,index)=>{const key=group.toLowerCase();const checked=key==='category'?((option==='All'&&!state.category)||(option===state.category)):state[key]===option;return `<label class="filter-option"><input type="radio" name="filter-${key}" value="${option}" ${checked?'checked':''}>${option}</label>`}).join('')}</div></details>`).join('');$('filterGroups').querySelectorAll('input').forEach(input=>input.addEventListener('change',()=>{const key=input.name.replace('filter-','');if(key==='category')state.category=input.value==='All'?'':input.value;else state[key]=input.value;renderCategories();renderProducts()}))}
function syncFilterInputs(){renderFilterGroups()}
function getFilteredProducts(){let result=laptops.filter(p=>{const query=state.query.trim().toLowerCase();const matchesQuery=!query||[p.name,p.brand,p.processor,p.gpu,p.category].join(' ').toLowerCase().includes(query);const matchesCategory=!state.category||p.category===state.category||(state.category==='Performance'&&['Gaming','Workstation'].includes(p.category));const matchesBrand=!state.brand||p.brand===state.brand;const matchesProcessor=!state.processor||p.processor===state.processor;const matchesRam=!state.ram||p.ram===state.ram;const matchesGpu=!state.gpu||(state.gpu==='RTX 4070 or higher'?p.gpu.startsWith('RTX 4070')||['RTX 4080','RTX 4090'].some(g=>p.gpu.includes(g)):p.gpu===state.gpu);let matchesPrice=true;const price=p.price;if(state.price){matchesPrice=state.price==='Under ₹40,000'?price<40000:state.price==='₹40,000 – ₹60,000'?price>=40000&&price<=60000:state.price==='₹60,000 – ₹80,000'?price>60000&&price<=80000:state.price==='₹80,000 – ₹1,00,000'?price>80000&&price<=100000:state.price==='₹1,00,000 – ₹1,50,000'?price>100000&&price<=150000:price>150000}return matchesQuery&&matchesCategory&&matchesBrand&&matchesProcessor&&matchesRam&&matchesGpu&&matchesPrice});switch(state.sort){case'price-asc':result.sort((a,b)=>a.price-b.price);break;case'price-desc':result.sort((a,b)=>b.price-a.price);break;case'rating':result.sort((a,b)=>b.rating-a.rating);break;case'discount':result.sort((a,b)=>discountOf(b)-discountOf(a));break}return result}
function productCard(p){const index=p.id-1;return `<article class="product-card"><div class="product-image-wrap"><img class="product-image" src="${p.image}" alt="${p.brand} ${p.name} laptop" loading="lazy" onerror="fallbackImage(this,${index})">${p.badge?`<span class="product-badge">${p.badge}</span>`:''}<span class="product-brand">${p.brand}</span></div><div class="product-info"><span class="product-category">${p.category==='AI PC'?'AI / Copilot+ PC':p.category+' laptop'}</span><h3 class="product-title">${p.name}</h3><div class="spec-list"><span class="spec-item" title="${p.processor}"><span>▣</span>${p.processor}</span><span class="spec-item"><span>▤</span>${p.ram} RAM</span><span class="spec-item"><span>▱</span>${p.storage}</span><span class="spec-item" title="${p.gpu}"><span>◈</span>${p.gpu}</span></div><div class="product-rating"><span class="stars">★★★★${p.rating>=4.7?'★':'☆'}</span><b>${p.rating.toFixed(1)}</b><span>·</span><span>${p.display}</span></div><div class="product-price-row"><b class="product-price">${formatPrice(p.price)}</b><span class="original-price">${formatPrice(p.originalPrice)}</span><span class="discount">${discountOf(p)}% off</span></div><button class="add-cart-button" data-add="${p.id}">Add to cart <span>＋</span></button></div></article>`}
function activeFilterChips(){const chips=[];for(const key of ['category','brand','processor','ram','gpu','price'])if(state[key])chips.push(`<span class="filter-chip">${state[key]}<button data-chip="${key}" aria-label="Remove ${state[key]} filter">×</button></span>`);if(state.query)chips.push(`<span class="filter-chip">“${escapeHtml(state.query)}”<button data-chip="query" aria-label="Clear search">×</button></span>`);return chips.join('')}
function escapeHtml(value){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function renderProducts(){const products=getFilteredProducts();$('resultsInfo').textContent=`Showing ${products.length} of ${laptops.length} laptops`;$('productGrid').innerHTML=products.map(productCard).join('');$('productGrid').hidden=!products.length;$('emptyState').hidden=!!products.length;$('activeFilters').innerHTML=activeFilterChips();$('productGrid').querySelectorAll('[data-add]').forEach(button=>button.addEventListener('click',()=>addToCart(Number(button.dataset.add))));$('activeFilters').querySelectorAll('[data-chip]').forEach(button=>button.addEventListener('click',()=>{state[button.dataset.chip]='';syncFilterInputs();if(button.dataset.chip==='query')$('catalogSearch').value='';renderCategories();renderProducts()}))}
function clearFilters(){state.category=state.brand=state.processor=state.ram=state.gpu=state.price=state.query='';$('catalogSearch').value='';$('navSearch').value='';syncFilterInputs();renderCategories();renderProducts()}
function addToCart(id){const product=laptops.find(p=>p.id===id);const existing=state.cart.find(item=>item.id===id);if(existing)existing.quantity++;else state.cart.push({id,quantity:1});saveCart();renderCart();showToast(`${product.name} added to your cart.`)}
function changeQuantity(id,delta){const item=state.cart.find(entry=>entry.id===id);if(!item)return;item.quantity+=delta;if(item.quantity<=0)state.cart=state.cart.filter(entry=>entry.id!==id);saveCart();renderCart()}
function removeFromCart(id){state.cart=state.cart.filter(item=>item.id!==id);saveCart();renderCart()}
function cartSubtotal(){return state.cart.reduce((total,item)=>total+laptops.find(p=>p.id===item.id).price*item.quantity,0)}
function renderCart(){const count=state.cart.reduce((n,item)=>n+item.quantity,0),subtotal=cartSubtotal(),delivery=subtotal===0||subtotal>=50000?0:99;$('cartCount').textContent=count;$('drawerItemCount').textContent=`(${count})`;$('cartItems').innerHTML=state.cart.map(item=>{const p=laptops.find(product=>product.id===item.id);return `<article class="cart-item"><img src="${p.image}" alt="${p.name}" onerror="fallbackImage(this,${p.id-1})"><div><h3>${p.name}</h3><small>${formatPrice(p.price)} each</small><div class="quantity-control"><button data-qty="${p.id}" data-delta="-1" aria-label="Decrease ${p.name} quantity">−</button><span>${item.quantity}</span><button data-qty="${p.id}" data-delta="1" aria-label="Increase ${p.name} quantity">+</button><button class="remove-item" data-remove="${p.id}">Remove</button></div></div><b class="cart-item-price">${formatPrice(p.price*item.quantity)}</b></article>`}).join('');$('cartItems').querySelectorAll('[data-qty]').forEach(button=>button.addEventListener('click',()=>changeQuantity(Number(button.dataset.qty),Number(button.dataset.delta))));$('cartItems').querySelectorAll('[data-remove]').forEach(button=>button.addEventListener('click',()=>removeFromCart(Number(button.dataset.remove))));$('cartEmpty').hidden=count>0;$('cartSummary').hidden=count===0;$('cartSubtotal').textContent=formatPrice(subtotal);$('cartDelivery').textContent=delivery===0?'FREE':formatPrice(delivery);$('deliveryHint').textContent=subtotal>0&&subtotal<50000?`Add ${formatPrice(50000-subtotal)} more for free delivery`:'Free delivery on orders ₹50,000 and above';$('cartTotal').textContent=formatPrice(subtotal+delivery);$('checkoutTotal').textContent=formatPrice(subtotal+delivery)}
function openCart(){ $('cartDrawer').classList.add('open');$('drawerScrim').classList.add('open');$('cartDrawer').setAttribute('aria-hidden','false');document.body.classList.add('lock-scroll')}
function closeCart(){ $('cartDrawer').classList.remove('open');$('drawerScrim').classList.remove('open');$('cartDrawer').setAttribute('aria-hidden','true');document.body.classList.remove('lock-scroll')}
function showToast(message){const toast=document.createElement('div');toast.className='toast';toast.textContent=message;$('toastRegion').append(toast);setTimeout(()=>toast.remove(),3000)}
function renderDeals(){const discounted=laptops.filter(p=>discountOf(p)>=9).sort((a,b)=>discountOf(b)-discountOf(a));const picks=[0,1].map(offset=>discounted[(state.dealOffset+offset)%discounted.length]);$('dealCards').innerHTML=picks.map(p=>`<article class="deal-card"><img src="${p.image}" alt="${p.name}" loading="lazy" onerror="fallbackImage(this,${p.id-1})"><div class="deal-copy"><span class="deal-label">${discountOf(p)}% OFF</span><h3>${p.name}</h3><small>${p.processor} · ${p.ram} RAM</small><div class="deal-price"><b>${formatPrice(p.price)}</b><del>${formatPrice(p.originalPrice)}</del><span>Save ${formatPrice(p.originalPrice-p.price)}</span></div></div></article>`).join('')}
function openCheckout(){if(!state.cart.length)return;closeCart();$('checkoutBackdrop').classList.add('open');$('checkoutBackdrop').setAttribute('aria-hidden','false');document.body.classList.add('lock-scroll');$('checkoutFormWrap').hidden=false;$('orderSuccess').hidden=true}
function closeCheckout(){ $('checkoutBackdrop').classList.remove('open');$('checkoutBackdrop').setAttribute('aria-hidden','true');document.body.classList.remove('lock-scroll')}
function placeOrder(event){event.preventDefault();const form=$('checkoutForm');if(!form.reportValidity())return;const order=`LPK${Math.floor(10000+Math.random()*90000)}`;$('orderId').textContent=`Order ID: ${order}`;$('checkoutFormWrap').hidden=true;$('orderSuccess').hidden=false;state.cart=[];saveCart();renderCart()}
function bindEvents(){$('catalogSearch').addEventListener('input',event=>{state.query=event.target.value;renderProducts()});$('navSearch').addEventListener('input',event=>{$('catalogSearch').value=event.target.value;state.query=event.target.value;renderProducts()});$('clearSearch').addEventListener('click',()=>{state.query='';$('catalogSearch').value='';$('navSearch').value='';renderProducts()});$('sortSelect').addEventListener('change',event=>{state.sort=event.target.value;renderProducts()});$('clearFilters').addEventListener('click',clearFilters);$('emptyClear').addEventListener('click',clearFilters);$('cartOpen').addEventListener('click',openCart);$('cartClose').addEventListener('click',closeCart);$('drawerScrim').addEventListener('click',closeCart);$('continueShopping').addEventListener('click',()=>{closeCart();$('laptops').scrollIntoView({behavior:'smooth'})});$('checkoutOpen').addEventListener('click',openCheckout);$('checkoutClose').addEventListener('click',closeCheckout);$('checkoutBackdrop').addEventListener('click',event=>{if(event.target===$('checkoutBackdrop'))closeCheckout()});$('checkoutForm').addEventListener('submit',placeOrder);$('orderDone').addEventListener('click',closeCheckout);$('dealPrev').addEventListener('click',()=>{state.dealOffset=(state.dealOffset+1)%laptops.length;renderDeals()});$('dealNext').addEventListener('click',()=>{state.dealOffset=(state.dealOffset+1)%laptops.length;renderDeals()});$('mobileMenuButton').addEventListener('click',()=>{const open=$('navLinks').classList.toggle('open');$('mobileMenuButton').setAttribute('aria-expanded',open)});$('navLinks').querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>$('navLinks').classList.remove('open')));$('filterOpen').addEventListener('click',()=>{$('filterPanel').classList.add('open');$('drawerScrim').classList.add('open');document.body.classList.add('lock-scroll')});$('filterClose').addEventListener('click',closeFilters);$('drawerScrim').addEventListener('click',closeFilters);$('filterPanel').addEventListener('click',event=>event.stopPropagation());document.querySelectorAll('[data-footer-category]').forEach(link=>link.addEventListener('click',()=>{state.category=link.dataset.footerCategory;syncFilterInputs();renderCategories();renderProducts()}));document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeCart();closeCheckout();closeFilters();$('navLinks').classList.remove('open')}})}
function closeFilters(){$('filterPanel').classList.remove('open');if(!$('cartDrawer').classList.contains('open'))$('drawerScrim').classList.remove('open');if(!$('cartDrawer').classList.contains('open')&&!$('checkoutBackdrop').classList.contains('open'))document.body.classList.remove('lock-scroll')}
renderCategories();renderFilterGroups();renderProducts();renderCart();renderDeals();bindEvents();
